---
- name: Show structure of current role
  hosts: podman_hosts
  become: true
  gather_facts: true

  vars:
    podman_user: podman
    podman_group: podman
    podman_search_registries:
      - "docker.io"
    podman_insecure_registries: []
  
  roles:
    - role: ../ansible-role-podman
