---
- name: Example playbook
  hosts: podman_hosts
  become: true
  gather_facts: true

  vars:
    container_storage: /opt/containers/storage
    podman_user: podman
    podman_group: podman
    podman_runtime: crun
  
  roles:
    - role: ../rootless_podman
