---
- name: Install packages
  ansible.builtin.include_tasks: install.yml

- name: Create sysctl conf file and reload
  ansible.builtin.include_tasks: sysctl.yml

- name: Create and configure user
  ansible.builtin.include_tasks: user.yml

- name: Set up config files
  ansible.builtin.include_tasks: config-files.yml

- name: Test basic container functionality
  ansible.builtin.include_tasks: test.yml
