---
# role: ansible-role-podman
# file: tasks/tasks.yml

- name: Set os_family dependent variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Set distribution dependent variables
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: True
  loop_control:
    loop_var: vars_file

- name: Include tasks for installing podman
  include_tasks: install.yml

- name: Include tasks for subuid/subgid mappings and user config
  include_tasks: users.yml

- name: Include tasks for config files and sysctl
  include_tasks: config-files.yml
  #when: podman_configure | bool
