---
- name: Pull an image
  become_user: "{{ podman_user }}"
  containers.podman.podman_image:
    name: "docker.io/library/httpd"
    tag: latest

- name: Copy kube file
  become_user: "{{ podman_user }}"
  ansible.builtin.copy: 
    src: test-kube.yml 
    dest: "{{ podman_user_home }}/test-kube.yml" 

- name: Play kube file
  become_user: "{{ podman_user }}"
  containers.podman.podman_play:
    kube_file: "{{ podman_user_home}}/test-kube.yml"
    state: started
